AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - "bin/console"
    - "test/rails_app/db/schema.rb"

Metrics/AbcSize:
  Exclude:
    - "test/**/*"

Metrics/LineLength:
  AllowHeredoc: true
  AllowURI: true
  IgnoreCopDirectives: true
  Max: 120
  Exclude:
    - "authorize_that.gemspec"
    - "test/**/*"

Metrics/MethodLength:
  Exclude:
    - "test/**/*"

Style/ClassAndModuleChildren:
  Exclude:
    - "test/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolProc:
  Exclude:
    - test/rails_app/db/migrate/20190708175731_create_tables.rb
