name: Main workflow

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.2

    - name: Install sqlite3
      run: sudo apt-get install libsqlite3-dev

    - name: Bundle
      run: |
        gem install bundler -v 1.17.3
        bundle install --jobs 4 --retry 3

    - name: Run rubocop
      run: bundle exec rubocop

    - name: Prepare test app
      run: |
        cd test/rails_app
        RAILS_ENV=test bundle exec rake db:migrate
        RAILS_ENV=development bundle exec rake db:migrate
        RAILS_ENV=production bundle exec rake db:migrate

    - name: Run tests
      run: bundle exec rake test
