name: Main workflow

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Docker image
      uses: docker://circleci/ruby:2.6.2

    - name: Bundle
      run: |
        bundle install

    - name: Run rubocop
      run: bundle exec rubocop
