name: Main workflow

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build the Docker image
      uses: docker build . --file Dockerfile

    - name: Bundle
      run: |
        gem install bundler -v "1.17.3"
        bundle install

    - name: Run rubocop
      run: bundle exec rubocop
