name: Main workflow

on: [push]

jobs:
  lint:
    steps:
    - name: Checkout
      uses: docker://circleci/ruby:2.6.2

    - name: Bundle
      run: |
        bundle install

    - name: Run rubocop
      run: bundle exec rubocop
