name: Main workflow

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run bundle
      run: |
        gem install bundler
        bundle install

    - name: Run rubocop
      run: bundle exec rubocop
