name: Main workflow

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: "2.6"

    - name: Bundle
      run: |
        gem install bundler
        bundle install

    - name: Run rubocop
      run: bundle exec rubocop
